name: Hello World Example

on: 
   workflow_dispatch:

jobs:
    hello_world_job:
        runs-on: ubunutu-latest
        steps: 
            - name: Hello World Step
              run: echo 'Hello World' # indent needs to match